[project]
name = "kalman"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipykernel>=6.29.5",
    "matplotlib>=3.10.0",
    "quantlib>=1.36",
    "scipy>=1.15.1",
    "yfinance>=0.2.51",
]
